### ISSUE TITLE
Installer no longer working

### ISSUE THREAD

**Issue by brunoman4006** [Xella37/CCDoom#1]
Installer is not working anymore (or at least not for me)

it says this after a second of starting the installer
![image](https://user-images.githubusercontent.com/54996905/230072345-f1a8925e-f1ce-4da8-bb79-3c16e2ba1456.png)
This image is if i run the code from pastebin
![image](https://user-images.githubusercontent.com/54996905/230072243-43235ff0-7b83-49a0-b2f4-c70f82c116f6.png)
This image is if i download the pastebin and then run it, but still not working

**Comment by Xella37** [comment]
Hi! Sorry for the late response, I've only just noticed the issue. The installer does not work because it's using my old name. I've changed my name on GitHub, so the links did not work for downloading. As far as I know, the installer should have been updated quite a while ago, but there might have been a brief period where the installer did not work.
